### ISSUE TITLE
Cannot start node since Pluto update: wrong number of args

### ISSUE THREAD

**Issue by theoturner** [fetchai/oef-core#3]
```
./oef-core-pluto-image/scripts/docker-run.sh --network host --
```
Result:
```
[docker-env.sh] DOCKER_IMAGE_TAG=oef-core-pluto-image
[docker-env.sh] DOCKER_CONTAINER_REGISTRY=gcr.io/organic-storm-201412
[docker-env.sh] DOCKER_LOCAL_MAKE=oef-core-pluto-image/scripts/docker-local-make.sh
[docker-env.sh] pwd=/Users/theo/DLM/nodes/fetch_node
[docker-env.sh] DOCKER_BUILD_CONTEXT_DIR=./oef-core-pluto-image/..
[docker-env.sh] DOCKERFILE=./oef-core-pluto-image/./Dockerfile
[docker-env.sh] DOCKER_ENV_SCRIPT_PATH=./oef-core-pluto-image/docker-env.sh
[docker-env.sh] http_proxy =
[docker-env.sh] https_proxy=
[docker-env.sh] no_proxy=
docker run -i -t -w /build --rm --network host -v /Users/theo/DLM/nodes/fetch_node:/build oef-core-pluto-image
Usage: node
Usage: node <core_key> <core_ip> <core_port> <search_ip> <search_port>
```
i.e. the node is not getting 5 args, as in [main.cpp](https://github.com/fetchai/oef-core/blob/61e54b8803d9bed3b828e58a7b436c0782a5b8a6/apps/node-pluto/src/main.cpp#L28).

I have the same behaviour regardless of whether I have a separate `oef-search-pluto` node running.

I did not have this problem before the Pluto update, where I ran with
```
./oef-core-image/scripts/docker-run.sh -p 3333:3333 -d --
```

**Comment by engineerkatie** [comment]
OEF core doesn't need to be run separately because it's now part of the docker image for oef-search-pluto. The two parts get run in a single container. We've updated the readme over at search to list the ports that can be connected to.

Apologies for the out-of-date docs -- our launch process should be much simplified in future releases including publishing ready-to-go docker images.

If you're still having problems, please come back to us and we'll do our best to help you out.

**Comment by theoturner** [comment]
Runs now on oef-mt-core
